name: bigwig-loader
channels:
  - rapidsai
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip
  - cython
  - c-compiler
  - kvikio>=24.06.00
  - cupy>=12.0.0
  - numpy>=1.21
  - pandas
  - pyfaidx
  - ncls
  - pydantic
  - pydantic-settings
  - python-dotenv
  - universal_pathlib
  - natsort
  - pip:
      - -e .[dev]
